applications:
- api_domain: docs.jit.io
  application_name: Jit Docs
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://docs.jit.io
  type: web
resource_management:
  runner_config:
    job_execution_timeout_minutes: 40
    job_setup_timeout_minutes: 20
    pr_job_execution_timeout_minutes: 30
    pr_job_setup_timeout_minutes: 15
